apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-b
  template:
    metadata:
      labels:
        app: mikroserwis-b
    spec:
      containers:
        - name: mikroserwis-b
          image: mkalejta/mikroserwis_b:1.0
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_DB
              value: testdb
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-b-service
spec:
  selector:
    app: mikroserwis-b
  ports:
    - port: 3000
      targetPort: 3000