apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-b
  template:
    metadata:
      labels:
        app: mikroserwis-b
    spec:
      containers:
        - name: mikroserwis-b
          image: mkalejta/mikroserwis_b:1.0
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: example
            - name: DB_NAME
              value: testdb
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-b-service
spec:
  selector:
    app: mikroserwis-b
  ports:
    - port: 3000
      targetPort: 3000