FROM nginx

RUN mkdir -p /etc/nginx/ssl

RUN apt-get update && \
    apt-get install -y openssl && \
    apt-get clean

RUN openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/key.pem \
    -x509 -days 365 -out /etc/nginx/ssl/certificate.pem \
    -subj "/CN=localhost"

RUN chown nginx:nginx /var/cache/nginx

COPY ./default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]