apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikroserwis-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikroserwis-a
  template:
    metadata:
      labels:
        app: mikroserwis-a
    spec:
      containers:
        - name: mikroserwis-a
          image: mkalejta/mikroserwis_a:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mikroserwis-a-service
spec:
  type: LoadBalancer
  selector:
    app: mikroserwis-a
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000