version: '3.8'
name: lab_07/zad_02
services:
  mongodb:
    image: mongo:$MONGO_VERSION
    container_name: db
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: my-db
    volumes:
      - ./data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - net_A
  server:
    image: mkalejta/api-server
    container_name: server
    depends_on:
      - mongodb
    networks:
      - net_A
    ports:
      - "3003:3003"


networks:
  net_A:
    name: net_A
    external: false