version: '3.8'
name: lab_08_zad_03
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express-app